"""Scalar bodies of the causal mask on the MFMA score layout (fmha_v4_causal.causal_mask).

Generated by scripts/gen_causal_mask.py -- edit that, not this file.

``gl.map_elementwise(..., pack=32)`` passes each thread's 32 score registers (a 32 x 64 slab
per wave, transposed 32x32 MFMA layout), then 32 copies each of the per-thread operands;
only the first copy (``d0``, ``k0``) is read, and the rest fold away.

  d0 = row - delta - 4 * (lane // 32)   per lane: the row minus the lane's first column
  k0 = 32 * wave - delta                 wave-uniform

Register e of a thread holds column ``e%4 + 8*(e//4 % 4) + 32*(e//16)`` plus 4 for the upper
half of the wave, so it is kept iff ``d0 >= COL[e]`` -- one compare against a compile-time
constant. That is what triton-tickets#812 asks of a causal mask: the per-element pattern is
known when the kernel is compiled, so nothing about it needs computing or keeping live.

``causal_mask_pack32`` uses the issue's three block states: per wave, each 32x32 block is
fully kept (no code), fully masked (16 moves of -inf), or the diagonal block (the compares).
The state is wave-uniform, so the branches skip whole blocks. ``causal_select_pack32`` does
the compare for every register, branch-free, for use inside a warp-pipelined loop.
"""

from triton.experimental import gluon
from triton.experimental.gluon import language as gl

NEG = gl.constexpr(float("-inf"))


@gluon.jit
def causal_mask_pack32(
    x0,
    x1,
    x2,
    x3,
    x4,
    x5,
    x6,
    x7,
    x8,
    x9,
    x10,
    x11,
    x12,
    x13,
    x14,
    x15,
    x16,
    x17,
    x18,
    x19,
    x20,
    x21,
    x22,
    x23,
    x24,
    x25,
    x26,
    x27,
    x28,
    x29,
    x30,
    x31,
    d0,
    d1,
    d2,
    d3,
    d4,
    d5,
    d6,
    d7,
    d8,
    d9,
    d10,
    d11,
    d12,
    d13,
    d14,
    d15,
    d16,
    d17,
    d18,
    d19,
    d20,
    d21,
    d22,
    d23,
    d24,
    d25,
    d26,
    d27,
    d28,
    d29,
    d30,
    d31,
    k0,
    k1,
    k2,
    k3,
    k4,
    k5,
    k6,
    k7,
    k8,
    k9,
    k10,
    k11,
    k12,
    k13,
    k14,
    k15,
    k16,
    k17,
    k18,
    k19,
    k20,
    k21,
    k22,
    k23,
    k24,
    k25,
    k26,
    k27,
    k28,
    k29,
    k30,
    k31,
):
    """Three states per wave and 32x32 block: block b (columns 32b .. 32b+31) is fully
    kept iff k0 >= 32b + 31, fully masked iff k0 <= 32b - 32, else the diagonal block.
    """
    if k0 < 31:
        if k0 <= -32:
            x0 = NEG
            x1 = NEG
            x2 = NEG
            x3 = NEG
            x4 = NEG
            x5 = NEG
            x6 = NEG
            x7 = NEG
            x8 = NEG
            x9 = NEG
            x10 = NEG
            x11 = NEG
            x12 = NEG
            x13 = NEG
            x14 = NEG
            x15 = NEG
        else:
            x0 = gl.where(d0 >= 0, x0, NEG)
            x1 = gl.where(d0 >= 1, x1, NEG)
            x2 = gl.where(d0 >= 2, x2, NEG)
            x3 = gl.where(d0 >= 3, x3, NEG)
            x4 = gl.where(d0 >= 8, x4, NEG)
            x5 = gl.where(d0 >= 9, x5, NEG)
            x6 = gl.where(d0 >= 10, x6, NEG)
            x7 = gl.where(d0 >= 11, x7, NEG)
            x8 = gl.where(d0 >= 16, x8, NEG)
            x9 = gl.where(d0 >= 17, x9, NEG)
            x10 = gl.where(d0 >= 18, x10, NEG)
            x11 = gl.where(d0 >= 19, x11, NEG)
            x12 = gl.where(d0 >= 24, x12, NEG)
            x13 = gl.where(d0 >= 25, x13, NEG)
            x14 = gl.where(d0 >= 26, x14, NEG)
            x15 = gl.where(d0 >= 27, x15, NEG)
    if k0 < 63:
        if k0 <= 0:
            x16 = NEG
            x17 = NEG
            x18 = NEG
            x19 = NEG
            x20 = NEG
            x21 = NEG
            x22 = NEG
            x23 = NEG
            x24 = NEG
            x25 = NEG
            x26 = NEG
            x27 = NEG
            x28 = NEG
            x29 = NEG
            x30 = NEG
            x31 = NEG
        else:
            x16 = gl.where(d0 >= 32, x16, NEG)
            x17 = gl.where(d0 >= 33, x17, NEG)
            x18 = gl.where(d0 >= 34, x18, NEG)
            x19 = gl.where(d0 >= 35, x19, NEG)
            x20 = gl.where(d0 >= 40, x20, NEG)
            x21 = gl.where(d0 >= 41, x21, NEG)
            x22 = gl.where(d0 >= 42, x22, NEG)
            x23 = gl.where(d0 >= 43, x23, NEG)
            x24 = gl.where(d0 >= 48, x24, NEG)
            x25 = gl.where(d0 >= 49, x25, NEG)
            x26 = gl.where(d0 >= 50, x26, NEG)
            x27 = gl.where(d0 >= 51, x27, NEG)
            x28 = gl.where(d0 >= 56, x28, NEG)
            x29 = gl.where(d0 >= 57, x29, NEG)
            x30 = gl.where(d0 >= 58, x30, NEG)
            x31 = gl.where(d0 >= 59, x31, NEG)
    return (
        x0,
        x1,
        x2,
        x3,
        x4,
        x5,
        x6,
        x7,
        x8,
        x9,
        x10,
        x11,
        x12,
        x13,
        x14,
        x15,
        x16,
        x17,
        x18,
        x19,
        x20,
        x21,
        x22,
        x23,
        x24,
        x25,
        x26,
        x27,
        x28,
        x29,
        x30,
        x31,
    )


@gluon.jit
def causal_select_pack32(
    x0,
    x1,
    x2,
    x3,
    x4,
    x5,
    x6,
    x7,
    x8,
    x9,
    x10,
    x11,
    x12,
    x13,
    x14,
    x15,
    x16,
    x17,
    x18,
    x19,
    x20,
    x21,
    x22,
    x23,
    x24,
    x25,
    x26,
    x27,
    x28,
    x29,
    x30,
    x31,
    d0,
    d1,
    d2,
    d3,
    d4,
    d5,
    d6,
    d7,
    d8,
    d9,
    d10,
    d11,
    d12,
    d13,
    d14,
    d15,
    d16,
    d17,
    d18,
    d19,
    d20,
    d21,
    d22,
    d23,
    d24,
    d25,
    d26,
    d27,
    d28,
    d29,
    d30,
    d31,
):
    """Branch-free: every register compares d0 against its own column."""
    x0 = gl.where(d0 >= 0, x0, NEG)
    x1 = gl.where(d0 >= 1, x1, NEG)
    x2 = gl.where(d0 >= 2, x2, NEG)
    x3 = gl.where(d0 >= 3, x3, NEG)
    x4 = gl.where(d0 >= 8, x4, NEG)
    x5 = gl.where(d0 >= 9, x5, NEG)
    x6 = gl.where(d0 >= 10, x6, NEG)
    x7 = gl.where(d0 >= 11, x7, NEG)
    x8 = gl.where(d0 >= 16, x8, NEG)
    x9 = gl.where(d0 >= 17, x9, NEG)
    x10 = gl.where(d0 >= 18, x10, NEG)
    x11 = gl.where(d0 >= 19, x11, NEG)
    x12 = gl.where(d0 >= 24, x12, NEG)
    x13 = gl.where(d0 >= 25, x13, NEG)
    x14 = gl.where(d0 >= 26, x14, NEG)
    x15 = gl.where(d0 >= 27, x15, NEG)
    x16 = gl.where(d0 >= 32, x16, NEG)
    x17 = gl.where(d0 >= 33, x17, NEG)
    x18 = gl.where(d0 >= 34, x18, NEG)
    x19 = gl.where(d0 >= 35, x19, NEG)
    x20 = gl.where(d0 >= 40, x20, NEG)
    x21 = gl.where(d0 >= 41, x21, NEG)
    x22 = gl.where(d0 >= 42, x22, NEG)
    x23 = gl.where(d0 >= 43, x23, NEG)
    x24 = gl.where(d0 >= 48, x24, NEG)
    x25 = gl.where(d0 >= 49, x25, NEG)
    x26 = gl.where(d0 >= 50, x26, NEG)
    x27 = gl.where(d0 >= 51, x27, NEG)
    x28 = gl.where(d0 >= 56, x28, NEG)
    x29 = gl.where(d0 >= 57, x29, NEG)
    x30 = gl.where(d0 >= 58, x30, NEG)
    x31 = gl.where(d0 >= 59, x31, NEG)
    return (
        x0,
        x1,
        x2,
        x3,
        x4,
        x5,
        x6,
        x7,
        x8,
        x9,
        x10,
        x11,
        x12,
        x13,
        x14,
        x15,
        x16,
        x17,
        x18,
        x19,
        x20,
        x21,
        x22,
        x23,
        x24,
        x25,
        x26,
        x27,
        x28,
        x29,
        x30,
        x31,
    )
