#!/usr/bin/env python3
"""Generate kernels/attention/fmha_causal_mask.py, the causal mask's scalar bodies.

``gl.map_elementwise(fn, qk, ..., pack=32)`` hands ``fn`` a thread's 32 score registers as
separate positional arguments, so a body that treats each register differently -- here,
by comparing it against its own compile-time column -- needs one parameter per register.
This writes those bodies for the fmha_v4/v5 score tile: BLOCK_N = 64, 32 rows per wave, the
transposed 32x32 MFMA layout.

Usage: python scripts/gen_causal_mask.py [output]   (default: the file above)
"""

import os
import sys

N = 32  # score registers per thread: a 32 x 64 slab per wave over 64 lanes

HEADER = '''"""Scalar bodies of the causal mask on the MFMA score layout (fmha_v4_causal.causal_mask).

Generated by scripts/gen_causal_mask.py -- edit that, not this file.

``gl.map_elementwise(..., pack=32)`` passes each thread's 32 score registers (a 32 x 64 slab
per wave, transposed 32x32 MFMA layout), then 32 copies each of the per-thread operands;
only the first copy (``d0``, ``k0``) is read, and the rest fold away.

  d0 = row - delta - 4 * (lane // 32)   per lane: the row minus the lane's first column
  k0 = 32 * wave - delta                 wave-uniform

Register e of a thread holds column ``e%4 + 8*(e//4 % 4) + 32*(e//16)`` plus 4 for the upper
half of the wave, so it is kept iff ``d0 >= COL[e]`` -- one compare against a compile-time
constant. That is what triton-tickets#812 asks of a causal mask: the per-element pattern is
known when the kernel is compiled, so nothing about it needs computing or keeping live.

``causal_mask_pack32`` uses the issue's three block states: per wave, each 32x32 block is
fully kept (no code), fully masked (16 moves of -inf), or the diagonal block (the compares).
The state is wave-uniform, so the branches skip whole blocks. ``causal_select_pack32`` does
the compare for every register, branch-free, for use inside a warp-pipelined loop.
"""

from triton.experimental import gluon
from triton.experimental.gluon import language as gl

NEG = gl.constexpr(float("-inf"))
'''


def col(e):
    return e % 4 + 8 * ((e // 4) % 4) + 32 * (e // 16)


def params(names):
    return "".join(f"    {a},\n" for a in names)


def ret(names):
    return "    return (\n" + "".join(f"        {x},\n" for x in names) + "    )\n"


def three_state(xs):
    out = []
    for b in (0, 1):
        lo = 16 * b
        out.append(f"    if k0 < {32 * b + 31}:\n")
        out.append(f"        if k0 <= {32 * b - 32}:\n")
        out += [f"            x{e} = NEG\n" for e in range(lo, lo + 16)]
        out.append("        else:\n")
        out += [
            f"            x{e} = gl.where(d0 >= {col(e)}, x{e}, NEG)\n" for e in range(lo, lo + 16)
        ]
    return "".join(out)


def main(path):
    xs = [f"x{e}" for e in range(N)]
    ds = [f"d{e}" for e in range(N)]
    ks = [f"k{e}" for e in range(N)]
    src = HEADER
    src += "\n\n@gluon.jit\ndef causal_mask_pack32(\n" + params(xs + ds + ks) + "):\n"
    src += (
        '    """Three states per wave and 32x32 block: block b (columns 32b .. 32b+31) is fully\n'
        "    kept iff k0 >= 32b + 31, fully masked iff k0 <= 32b - 32, else the diagonal block.\n"
        '    """\n'
    )
    src += three_state(xs) + ret(xs)
    src += "\n\n@gluon.jit\ndef causal_select_pack32(\n" + params(xs + ds) + "):\n"
    src += '    """Branch-free: every register compares d0 against its own column."""\n'
    src += "".join(f"    x{e} = gl.where(d0 >= {col(e)}, x{e}, NEG)\n" for e in range(N))
    src += ret(xs)
    with open(path, "w") as f:
        f.write(src)


if __name__ == "__main__":
    default = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "..",
        "kernels",
        "attention",
        "fmha_causal_mask.py",
    )
    main(sys.argv[1] if len(sys.argv) > 1 else default)
